// config.js — written COMPLETE at scaffold time. Other modules import from here.
// Do NOT edit this file in later phases; it is the single source of truth for
// paths, ports, and the context-window helper.

import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Repository root: this file lives at <repo>/server/src/config.js, so go up two levels.
const REPO_ROOT = path.resolve(__dirname, '..', '..');

/**
 * Absolute path to Claude Code's projects directory: ~/.claude/projects.
 * The scanner/parser read ONLY inside this directory, and DELETE is the only
 * write operation ever allowed under it.
 *
 * Overridable via the KANBAI_PROJECTS_DIR env var (used by tests and demos to
 * point Kanbai at an isolated dataset instead of the real ~/.claude/projects).
 * @type {string}
 */
export const CLAUDE_PROJECTS_DIR =
  process.env.KANBAI_PROJECTS_DIR && process.env.KANBAI_PROJECTS_DIR.length > 0
    ? path.resolve(process.env.KANBAI_PROJECTS_DIR)
    : path.join(os.homedir(), '.claude', 'projects');

/**
 * Absolute path to the local Kanban state file: <repo>/data/store.json.
 * @type {string}
 */
export const STORE_PATH = path.join(REPO_ROOT, 'data', 'store.json');

/**
 * Backend HTTP port. Defaults to 4319, overridable via the KANBAI_PORT env var.
 * @type {number}
 */
export const PORT = Number.parseInt(process.env.KANBAI_PORT ?? '', 10) || 4319;

/**
 * Default context window (tokens) used when the model id is unknown.
 * @type {number}
 */
export const DEFAULT_CONTEXT_WINDOW = 200_000;

/**
 * Large (1M) context window used when the model id advertises a 1m variant.
 * @type {number}
 */
export const LARGE_CONTEXT_WINDOW = 1_000_000;

/**
 * Resolve the context window (in tokens) for a given model id.
 * Returns 1_000_000 when the model id contains a "1m" marker (e.g. "[1m]",
 * "-1m"), otherwise 200_000. Falsy/unknown models fall back to the default.
 *
 * @param {string|null|undefined} model - Model identifier, e.g. "claude-opus-4-7".
 * @returns {number} Context window size in tokens.
 */
export function getContextWindow(model) {
  if (model && /1m/i.test(model)) {
    return LARGE_CONTEXT_WINDOW;
  }
  return DEFAULT_CONTEXT_WINDOW;
}

/**
 * Decode an encoded project directory name back into a filesystem path
 * (best effort). Claude Code encodes a cwd by replacing every "/" with "-",
 * so a leading "-" maps to the leading "/". Inner dashes that were part of
 * real path segments (hyphenated names, worktrees, dotfiles) cannot be
 * perfectly recovered, so this reconstruction is LOSSY BY DESIGN.
 *
 * It is only a display fallback: sessionParser.js prefers the authoritative
 * `cwd` recorded verbatim on each session line and falls back here just when no
 * line carried a cwd. Do not rely on this round-tripping the original path.
 *
 * @example
 *   decodeProjectDir('-Users-x-y') // => '/Users/x/y'
 *
 * @param {string} name - Encoded directory name.
 * @returns {string} Best-effort, lossy decoded path (display fallback only).
 */
export function decodeProjectDir(name) {
  if (typeof name !== 'string' || name.length === 0) {
    return '';
  }
  // Replace every dash with a slash. A leading dash becomes a leading slash,
  // yielding an absolute path on POSIX systems.
  return name.replace(/-/g, '/');
}
